/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/shared/Button.vue')['default']
    FileUpload: typeof import('./src/components/shared/FileUpload.vue')['default']
    Gift: typeof import('./src/components/home/Gift.vue')['default']
    GiftsList: typeof import('./src/components/home/GiftsList.vue')['default']
    GiftsModal: typeof import('./src/components/home/GiftsModal.vue')['default']
    Modal: typeof import('./src/components/shared/Modal.vue')['default']
    Navigation: typeof import('./src/components/shared/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserEventList: typeof import('./src/components/home/UserEventList.vue')['default']
    UserSelectedGift: typeof import('./src/components/home/UserSelectedGift.vue')['default']
  }
}
